dependencies:
- XlsxWriter =1.3,<2
- python-pptx >=0.6.18
- docopt >=0.6
- notebook
- livereload =2
- flake8
- pandas
- msal
- seaborn
- statsmodels
- scikit-learn
- seedbank
- jupyterlab
- pip:
  - tinytag ~=1.5
category: dev
